2022-04-06 01:51:49,290 INFO    MainThread:29490 [wandb_setup.py:_flush():75] Loading settings from /home/ltorres/.config/wandb/settings
2022-04-06 01:51:49,290 INFO    MainThread:29490 [wandb_setup.py:_flush():75] Loading settings from /home/ltorres/leo/tesis/cloud-classification/code/wandb/settings
2022-04-06 01:51:49,290 INFO    MainThread:29490 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-04-06 01:51:49,290 INFO    MainThread:29490 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-04-06 01:51:49,290 INFO    MainThread:29490 [wandb_init.py:_log_setup():405] Logging user logs to /home/ltorres/leo/tesis/cloud-classification/code/wandb/run-20220406_015149-24cdgd9w/logs/debug.log
2022-04-06 01:51:49,290 INFO    MainThread:29490 [wandb_init.py:_log_setup():406] Logging internal logs to /home/ltorres/leo/tesis/cloud-classification/code/wandb/run-20220406_015149-24cdgd9w/logs/debug-internal.log
2022-04-06 01:51:49,290 INFO    MainThread:29490 [wandb_init.py:_jupyter_setup():355] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f064c187700>
2022-04-06 01:51:49,291 INFO    MainThread:29490 [wandb_init.py:init():439] calling init triggers
2022-04-06 01:51:49,291 INFO    MainThread:29490 [wandb_init.py:init():442] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0003, 'architecture': 'GATConvGNN', 'loss': 'LogeLoss', 'optim': 'SGD', 'dataset': 'GCD', 'builder': 'Cosine Similarity', 'epochs': 15}
2022-04-06 01:51:49,291 INFO    MainThread:29490 [wandb_init.py:init():492] starting backend
2022-04-06 01:51:49,291 INFO    MainThread:29490 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-04-06 01:51:49,327 INFO    MainThread:29490 [backend.py:ensure_launched():219] starting backend process...
2022-04-06 01:51:49,357 INFO    MainThread:29490 [backend.py:ensure_launched():224] started backend process with pid: 29700
2022-04-06 01:51:49,359 INFO    MainThread:29490 [wandb_init.py:init():501] backend started and connected
2022-04-06 01:51:49,375 INFO    MainThread:29490 [wandb_run.py:_label_probe_notebook():947] probe notebook
2022-04-06 01:51:49,375 INFO    MainThread:29490 [wandb_run.py:_label_probe_notebook():957] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-04-06 01:51:49,376 INFO    MainThread:29490 [wandb_init.py:init():565] updated telemetry
2022-04-06 01:51:49,456 INFO    MainThread:29490 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-04-06 01:51:50,260 INFO    MainThread:29490 [wandb_run.py:_on_init():1759] communicating current version
2022-04-06 01:51:50,339 INFO    MainThread:29490 [wandb_run.py:_on_init():1763] got version response upgrade_message: "wandb version 0.12.12 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-04-06 01:51:50,339 INFO    MainThread:29490 [wandb_init.py:init():625] starting run threads in backend
2022-04-06 01:51:51,957 INFO    MainThread:29490 [wandb_run.py:_console_start():1733] atexit reg
2022-04-06 01:51:51,958 INFO    MainThread:29490 [wandb_run.py:_redirect():1606] redirect: SettingsConsole.WRAP
2022-04-06 01:51:51,959 INFO    MainThread:29490 [wandb_run.py:_redirect():1643] Wrapping output streams.
2022-04-06 01:51:51,960 INFO    MainThread:29490 [wandb_run.py:_redirect():1667] Redirects installed.
2022-04-06 01:51:51,960 INFO    MainThread:29490 [wandb_init.py:init():664] run started, returning control to user process
2022-04-06 01:51:51,968 INFO    MainThread:29490 [wandb_init.py:_pause_backend():318] pausing backend
2022-04-06 01:51:51,968 INFO    MainThread:29490 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-04-06 01:51:52,000 INFO    MainThread:29490 [wandb_init.py:_resume_backend():327] resuming backend
2022-04-06 02:09:02,874 INFO    MainThread:29490 [wandb_init.py:_pause_backend():318] pausing backend
2022-04-06 02:09:02,874 INFO    MainThread:29490 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-04-06 02:10:09,205 INFO    MainThread:29490 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 0
2022-04-06 02:10:09,207 INFO    MainThread:29490 [wandb_run.py:_restore():1674] restore
